/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) {
        // Création d'un bouton
        Button button = new Button("Cliquez-moi !");
        button.setOnAction(event -> System.out.println("Bouton cliqué !"));

        // Création d'un conteneur pour le bouton
        StackPane root = new StackPane(button);

        // Création de la scène
        Scene scene = new Scene(root, 400, 300);

        // Configuration de la fenêtre principale
        primaryStage.setTitle("Application JavaFX de Base");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args); // Lance l'application JavaFX
    }
}
